<Project>
	<PropertyGroup Condition="'$(Version)' == ''">
		<Version>1.0.0.0</Version>
	</PropertyGroup>
	<PropertyGroup Condition="'$(SignAssembly)' == 'true'">
		<DefineConstants>$(DefineConstants);SIGN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup>
		<ArtifactsDir Condition="'$(ArtifactsDir)' == ''">$(SolutionDir)..\bin\$(SolutionName)</ArtifactsDir>
		<OutputPath Condition="'$(IsTestProject)' != 'true'">$(ArtifactsDir)</OutputPath>
		<AppendTargetFrameworkToOutputPath>True</AppendTargetFrameworkToOutputPath>
		<BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\..\..\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<TestArtifactsDir Condition="'$(TestArtifactsDir)' == ''">$(SolutionDir)..\bin-tests\$(SolutionName)</TestArtifactsDir>
		<OutputPath>$(TestArtifactsDir)</OutputPath>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
</Project>